# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdd9459e7a4b10fa1f68ca96243045a611a257f9a6d6c5e883731a90758e7eaf283d9bdf089aae49c4a19fc64b8f13e737fdd310c38e312469dcea58e51c0516

test:
  secret_key_base: 09a284a6c5d5caa84156088bcb861b7f8af324c43406efd734ce958c6378bad4bf29652c96eec2d405d36313fef5f7c2b058b12925e48ecbb166d39948512375

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
